import Head from "next/head";

export default function Page() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta content="Generated by create next app" name="description" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <main>
        <h1 className="text-2xl md:text-5xl lg:text-9xl font-bold">
          Hello, Next.js!
        </h1>
      </main>
    </>
  );
}
