import "./globals.css";

import { Figtree } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const figtree = Figtree({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-figtree",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${figtree.variable} font-sans font-light bg-gray-900 text-gray-100`}
      >
        <div className="container mx-auto">{children}</div>
      </body>
    </html>
  );
}
