import "./globals.css";

import { Figtree } from "next/font/google";
import Image from "next/image";
import Link from "next/link";
import { BsDribbble, BsGithub, BsInstagram, BsLinkedin } from "react-icons/bs";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const figtree = Figtree({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-figtree",
});

const navLinks = [
  { name: "HOME", link: "/" },
  { name: "ABOUT ME", link: "/about" },
  { name: "PROJECTS", link: "/projects" },
  { name: "BLOG", link: "/blog" },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${figtree.variable} font-sans font-light bg-gray-900 text-gray-100 mainGrid`}
      >
        <div className="bg-gray-800 relative h-screen">
          <div className="bg-gray-800 fixed px-2 h-screen w-[120px] text-center flex flex-col item-center justify-center">
            <Image
              alt="logo"
              className="mb-10 mx-auto"
              height={100}
              src="/logo.png"
              width={100}
            />
            <div>
              {navLinks.map((link) => (
                <Link href={link.link} key={link.name}>
                  <div className="my-2 py-3 hover:bg-purple-900 duration-300 rounded-xl">
                    {link.name}
                  </div>
                </Link>
              ))}
            </div>
          </div>
        </div>
        <div className="container mx-auto">{children}</div>
        <div className="bg-gray-800  h-screen">
          <div className="fixed bottom-0 bg-gray-800 w-[80px] h-screen  text-center flex flex-col item-center justify-end pb-20">
            <Link
              href="https://www.linkedin.com/in/dilipchandima/"
              target={"_blank"}
            >
              <div className="text-2xl text-gray-400 hover:text-purple-600 py-5 flex items-center justify-center">
                <BsLinkedin />
              </div>
            </Link>
            <Link href="https://github.com/dilipchandima" target={"_blank"}>
              <div className="text-2xl text-gray-400 hover:text-purple-600 py-5 flex items-center justify-center">
                <BsGithub />
              </div>
            </Link>
            <Link href="https://dribbble.com/dilipchandima" target={"_blank"}>
              <div className="text-2xl text-gray-400 hover:text-purple-600 py-5 flex items-center justify-center">
                <BsDribbble />
              </div>
            </Link>
            <Link
              href="https://www.instagram.com/dilipchandima/"
              target={"_blank"}
            >
              <div className="text-2xl text-gray-400 hover:text-purple-600 py-5 flex items-center justify-center">
                <BsInstagram />
              </div>
            </Link>
          </div>
        </div>
      </body>
    </html>
  );
}
